### PR TITLE
Nginx and LFS compliance enhancements

### PR DESCRIPTION
**Pull request by rzerres**
# LFS compliance adaptions

* Makefile: /var/run is depreciated -> using /run
* Makefile: add missing include for "letsencrypt.toml"

acmed.service: sandbox hardened systemd unit
  * RuntimeDirectory (systemd handled access to pid-file)
acmed.conf: systemd handled tempfile configuration
  * preset runtime environment, needed
    if daemon is started without systemd unit
  * asure writable LFS compliant directories,
  * assining an `acmed` system user
    create the user with your OS tools (e.g useradd)
letsencrypt.toml: update strings

# Introduce a nginx hook
  the hook will resolve the new environment variables
   * NGINX_CONFDIR -> default: /etc/nginx/conf.d
   * NGINX_CHALLENGE_LOCTION -> default: 001-challenge-letsencrypt.conf
   * NGINX_TLS_CERTIFICATE -> default:002-tls-certificates.conf

  - group: nginx-config-challenge-location
    this will generate -> $NGINX_CONFDIR/$NGINX_CHALLENGE_LOCATION
  - group: nginx-config-certificate-location
    this will generate -> $NGINX_CONFDIR/$NGINX_TLS_CERTIFICATE

  ACMEd amims to minimize the amount of ReadWrite directories. The systemd.unit
  (acmed.service), takes advantage of sandbox capabilities.

  For nginx support, we need to ReadWrite to $NGINX_CONFDIR.  Since
  we are running with uid/gid of 'acmed' and probably aren't
  authorized, an user with administrative rights need to call once

     chmod g+w $NGINX_CONFIR

  on systemd managed systems, we are able to correct/rewrite the directory
  rights at installation time (tmpfiles.d/acmed.conf).

  A website admin needs to include

   * $NGINX_CHALLENGE_LOCATION and
   * $NGINX_TLS_CERTIFICATE

  inside the  [virtual-]host configuration block of websites to
  activate the templates (non automated task)

- adapt acmed.service
  will hint to NGINX environment variables
  defaults are handled inside the nginx hook
- adapt tempfiles.d/acmed.conf
  preset default directory to store challenges (if acmed isn't started
  via systemd)
- adapat Makefile
  add nginx_hooks.toml

### CODE REVIEW

**Comment by breard-r** [comment]
Thank you very much, this help is much appreciated.

However, I would prefer if you could split this PR into several ones so it's easier to merge. Ideally, there should be:
- one PR for the `/var/run` → `/run` (which should update the `CHANGELOG.md` and also changes the value in both `acmed/build.rs` and `tacd/build.rs`)
- one PR for the missing `letsencrypt.toml` file during the installation
- one PR for the reworked `acmed.service` file and the new `tmpfiles.d/acmed.conf` that comes along
- one PR for the reworked `letsencrypt.toml` file
- one PR for the nginx hooks ([tagged as a draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/) since I think it still needs some adjustments, specially because the template engine will change in the next few days)

**Comment by rzerres** [comment]
Fine, 

I will brake it up and send a new PR.

**Comment by rzerres** [comment]
I looked into it and didn't come up with a practical solution using the Github model of the API:

* Github will assemble all commits in the souce branch of a PR. No chance to brake them with ease in standalone PR's.
* You are able to difference the changes in small chunks: commits. This will resolve the dependencies and the possible automation tasks will work on the complete PR.
* If you want't to use distinctable PR's you need to work with distinctable branches. Apply all the commits you want to combine in that branch. This can be send to upstream.
* Having different PR's implicitely requires, that the included commits do not depend on other PR's. Thus if PR2 depends on PR2, the API can't figure that out programmatically. At least I couldn't figure out howto do that in a meaningful way.

As a conclusion, i will try to do separate PRs, if the given commits will work in row without depending on a merge of another PR in orign (here: your main branch).

Other then this, i think it is most convenient to cherry pick the commits in order of their appearence in the PR.

**Comment by rzerres** [comment]
This is superceeded with #47 and #48

**Comment by breard-r** [comment]
Could you open another PR for the service file please?

**Pull request closed without merging**
